version: "3.8"
services:
  db:
    container_name: fiber_db
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root    
    volumes:
      - tb_pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    restart: always
  pgadmin4:
    container_name: fiber_pgadmin
    image: elestio/pgadmin:REL-8_8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - tb_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db    
    restart: always
  fibertest-service:
    image: yoshikrit/fiber-test:latest
    container_name: fibertest-service
    ports:
      - 8081:8081
    links:
      - "db:db"
    depends_on:
      - db
    restart: on-failure

volumes:
  tb_pgdata:
    name: tb_pgdata
  tb_pgadmin_data:
    name: tb_pgadmin_data