version: "3.8"
services:
  postgresql:
    container_name: fiber_db
    image: postgres
    environment:
      POSTGRES_DATABASE: teletubbies
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: "Asia/Bangkok"
    ports:
      - 5432:5432
    volumes:
      - C:\\Users\\acer\\Desktop\\teletubbies-cafe\\PostgresDB:/var/lib/postgresql/data
    restart: on-failure
  pgadmin4:
    container_name: fiber_pgadmin4
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgresql
  fibertest-service:
    image: yoshikrit/fiber-test:latest
    container_name: fibertest-service
    ports:
      - 8081:8081
    links:
      - "postgresql:postgresql"
    depends_on:
      - postgresql
    restart: on-failure