BEGIN;

-- Truncate data in table
TRUNCATE TABLE "user" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;
TRUNCATE TABLE "role" CASCADE;
TRUNCATE TABLE "producttype" CASCADE;

-- Drop tables
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "oauth" CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS "producttype" CASCADE;

COMMIT;